### ISSUE TITLE
zabbix-ipsec.pyis mixing spaces and tabs

### ISSUE THREAD

**Issue by jcgonnard** [alanwds/zabbix_ipsec_pfsense#13]
Hi

there are some indentation issues in this file which leads to some errors while using with python3.7

- **formatIkeId** and **parseConf**  functions are mixing space and tab indentation
- **findDescr** is using 8 spaces indentation and **parseConf**,  **getTemplate**, **getPayload** and the **main** are using 4 paces indentation

**Comment by alanwds** [comment]
Fixed in [#13](https://github.com/alanwds/zabbix_ipsec_pfsense/tree/%2313)
