### ISSUE TITLE
It can't see the secondary Phase 2 entry.

### ISSUE THREAD

**Issue by krolingo** [alanwds/zabbix_ipsec_pfsense#5]
This script is awesome and it has been working for me great so far. The issue I'm having is that after adding an additional phase2 entry, to gain access to an additional VLAN, but I can't monitor the second connection. 

The VPN connection as two conX000 entries one is Con5000 and the added phase 2 entry comes as con5001, con5000 is monitored whereas con5001 is not. The phase2 descriptions are different as to not conflict with each other.

**Comment by alanwds** [comment]
@krolingo Looks like a problema on tunnels discovery. Have you tried run the script on pfsense shell?

/usr/local/bin/python2.7 /usr/local/bin/zabbix-ipsec.py

You should get something like that:

```
/usr/local/bin/python2.7 /usr/local/bin/zabbix-ipsec.py
{
    "data":[
        { "{#TUNNEL}":"con5001","{#TARGETIP}":" X.X.X.X","{#SOURCEIP}":" X.X.X.X","{#DESCRIPTION}":"Your description for con5001" },
        { "{#TUNNEL}":"con5002","{#TARGETIP}":" X.X.X.X","{#SOURCEIP}":" X.X.X.X","{#DESCRIPTION}":"Your description for con5001" }
    ]
}
```
